sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lj20040905
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRJtDDGRhDwjejGNM4s
    access-key-secret: OuiF09dQjh9eRhDYyluzmnJcmRQV6s
    bucket-name: sky-lijun
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wxd4652be0bfbbb582
    secret: 4722294aa1af72ad320bb17c9abc9c54